### PR TITLE
[WIP] Add before insert event

### PR DESCRIPTION
**Pull request by jacob-andersson**
- Add new before insert event to be able to add loading indicators in apps that uses the gem

### CODE REVIEW

**Comment by jgorset** [comment]
We want to move displaying the loading indicator into this gem, too, but for now we're going to point to this branch (so please don't merge it yet).

**Comment by toothfairy** [comment]
I really like the idea about indicator!

**Comment by jgorset** [comment]
Y U DO DIS PETER

**Comment by sindrenm** [comment]
El OL.

**Pull request merged**
