### PR TITLE
Fixed some typos.

### PR DESCRIPTION
**Pull request by sullysaurus**

### CODE REVIEW

**Comment by nashby** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by sindrenm** [comment]
Good eye, @danny-sullivan, thanks for yoir PR! :ok_hand:

**Comment by sullysaurus** [comment]
Sure thing :+1:

**Comment by jgorset** [comment]
> Good eye, @danny-sullivan, thanks for yoir PR! :ok_hand:
> 
> > thanks for yoir PR! :ok_hand:
> > 
> > > yoir PR!
> > > 
> > > > yoir

200_s

**Comment by sindrenm** [comment]
Yoi just had to pount it oit, didn't yoi?

**Pull request merged**
