### PR TITLE
Explicitly request html

### PR DESCRIPTION
**Pull request by jacob-andersson**
- Explicitly fetch html
- Bump version

### CODE REVIEW

**Comment by sindrenm** [comment]
Did you try adding an Accept header to the jQuery request instead? I think that would be a little bit cleaner. :smiley:

**Comment by toothfairy** [comment]
I certainly like it, even though I don't understand when it might respond with something but html

**Comment by jacob-andersson** [comment]
Apparently you can end up getting json instead of html (most likely due to global backend settings) :/

**Comment by sindrenm** [comment]
My guess is that `$.get` asks for JSON by default now (probably something that has changed after we created this), and that's essentially fucking things up now. Either adding this _.html_ format or setting a Accept header should do the trick. I'm leaning more towards the header approach if you can get that to work. If not, then I'm perfectly fine with this one as well. :smiley:

**Comment by jacob-andersson** [comment]
@sindrenm: It already uses an Accept-header ;)

**Comment by sindrenm** [comment]
Oh, sorry, didn't see the new commit you made! Yeah, I approve of this as well. :+1:

**Pull request merged**
